consul:
    image: consul:latest
    # command: agent -dev
    hostname: consul
    # network_mode : host
    privileged: false
    restart: always
    ports:
    - 8500:8500
    - 8600:8600/udp
    environment:
    - SERVICE_8300_IGNORE=yes
    - SERVICE_8301_IGNORE=yes
    - SERVICE_8302_IGNORE=yes
    - SERVICE_8400_IGNORE=yes
    - SERVICE_53_NAME=consul-dns
    - SERVICE_8500_NAME=consul-http

registrator:
    image: gliderlabs/registrator
    command: -internal consul://localhost:8500
    hostname: registrator
    net : host
    privileged: false
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock