consul:
    image: consul:latest
    # command: agent -dev
    hostname: consul
    # network_mode : host
    privileged: false
    restart: always
    ports:
    - 8500:8500
    - 8600:8600/udp
    environment:
    - SERVICE_8300_IGNORE=yes
    - SERVICE_8301_IGNORE=yes
    - SERVICE_8302_IGNORE=yes
    - SERVICE_8400_IGNORE=yes
    - SERVICE_53_NAME=consul-dns
    - SERVICE_8500_NAME=consul-http

registrator:
    image: gliderlabs/registrator
    command: -internal consul://localhost:8500
    hostname: registrator
    net : host
    privileged: false
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

mongodb:
    image: mongo:latest
    hostname: mongo
    privileged: false
    restart: always
    ports: 
    - 27017
    volumes:
    - ./volumes/db/mongo:/data/db

mongo-express:
    image: mongo-express:latest
    hostname: mongo-express
    privileged: false
    restart: always
    links:
    - mongodb:mongo
    ports:
    - 8081:8081

kamon-grafana-dashboard:
    image: kamon/grafana_graphite:latest
    hostname: kamon-grafana-dashboard
    privileged: false
    restart: always
    dns:
    - 172.17.0.1
    ports:
    - 8082:80
    - 8125:8125/udp
    - 8126:8126
    - 8083:81
    environment:
    - SERVICE_8126_IGNORE=yes
    - SERVICE_81_IGNORE=yes
    - SERVICE_80_NAME=grafana-dashboard
    - SERVICE_8125_NAME=statd