consul:
    image: index.docker.io/progrium/consul:latest
    command: -server -bootstrap -advertise 120.26.104.246 -ui-dir /ui
    hostname: consul
    privileged: false
    restart: always
    ports:
    - 8500:8500
    - 53:53/udp
    environment:
    - SERVICE_8300_IGNORE=yes
    - SERVICE_8301_IGNORE=yes
    - SERVICE_8302_IGNORE=yes
    - SERVICE_8400_IGNORE=yes
    - SERVICE_53_NAME=consul-dns
    - SERVICE_8500_NAME=consul-admin_infra
registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    hostname: registrator
    privileged: false
    restart: always
    links:
    - consul
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
mongodb:
    image: mongo
    privileged: false
    restart: always
    ports:
    - 27017
    volumes:
    - /data/db/mongo:/data/db
mongo-express:
    image: mongo-express
    privileged: false
    restart: always
    links:
    - mongodb:mongo
    ports:
    - 8081:8081
kamon-grafana-dashboard:
    image: kamon/grafana_graphite
    privileged: false
    restart: always
    ports:
    - 8082:80
    - 8125:8125/udp
    - 8126:8126
    - 8083:81
    environment:
    - SERVICE_8126_IGNORE=yes
    - SERVICE_81_IGNORE=yes
    - SERVICE_80_NAME=grafana-dashboard
    - SERVICE_8125_NAME=statd
