// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Chat
*/
package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type Chat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto1.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}

type Chat_Nil struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Chat_Nil) Reset()         { *m = Chat_Nil{} }
func (m *Chat_Nil) String() string { return proto1.CompactTextString(m) }
func (*Chat_Nil) ProtoMessage()    {}

type Chat_Message struct {
	Id               *uint64 `protobuf:"varint,1,opt" json:"Id,omitempty"`
	Body             []byte  `protobuf:"bytes,2,opt" json:"Body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Chat_Message) Reset()         { *m = Chat_Message{} }
func (m *Chat_Message) String() string { return proto1.CompactTextString(m) }
func (*Chat_Message) ProtoMessage()    {}

func (m *Chat_Message) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chat_Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Chat_Id struct {
	Id               *uint64 `protobuf:"varint,1,opt" json:"Id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Chat_Id) Reset()         { *m = Chat_Id{} }
func (m *Chat_Id) String() string { return proto1.CompactTextString(m) }
func (*Chat_Id) ProtoMessage()    {}

func (m *Chat_Id) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func init() {
}
